* day 0 <2017-07-05 周三>
I am extremely cross.生气
cross a.生气

OK, so what sort of person would put a cryptic note in a newspaper advert?
cryptic a.隐秘的；秘密的；隐晦的

egomaniac,needy,game-player
n. 极端利己主义者；自大狂

dormant a.休眠的；静止的

cyborg n.半机械人；靠机械装置维持生命的人

* day 1<2017-07-06 周四>
** Conversation Expression
1. If you ask me:opinion
2. Speaking of...,=linking new topic to old topic
3. As I was saying,=go back to earlier point in conversation

** Passed or Past?
| Past          | Passed         |
|---------------+----------------|
| Think time    | Think movement |
| *Noun*        | *Verb*         |
| Before        | 1) To go by    |
| *Adjective*   | 2) To go away  |
| Before        | 3) To succeed  |
| *Preposition* |                |
| After         |                | 

The house past the church

Examples:
1. I *passed* the supermarket on my way to school.
2. In the *past*, dinosaurs walked the Earth.
3. Archaeologists study *past* cultures.
4. I *passed* my test by studying *past* tests.
 
** Slang in English:"What the hell"
hell = n.
1. interjection n.感叹词 What the hell! 
intensifier n.强调成分:
 - What _the hell_ happened?
 - Who _the hell_ is that?
 - When _the hell_ did you get married?
 - Where _the hell_ are my keys?
 - How _the hell_ do I fix this?
 - Hell no!/Hell yeah!

 - Expressions with hell
   1. Give someone hell = reproach n.责备；耻辱 v.责备

   2. Go to hell!(very very rude)

   3. To/The hell with _it/her/studying_!
      means I don't care about her.
   4. For the hell of it = no reason  fun
   5. Like hell = great speed/reckless a.鲁莽的；不计后果的
   6. When hell freezes over = never
      e.g. I will go out with Bob when hell freezes over. 

axe a. 斧；解雇 vt. 用斧砍；解雇

ash n. 灰

bend v. 弯曲；屈服 n.弯曲；弯道

det n. 债务；恩情

consonant n. 辅音

sibilant

* day 2 <2017-07-11 Tue 07:15>
** Vocabulary you must have for IELTS test band 8 | Topic Food

*** quality justifies the bill
when a product is worth buying due its good quality, even if it's expensive.
e.g. I first thought those strawberries were too expensive, but when I tasted them I understood that their quality justified the bill.

*** to wine and dine
to banquet(n. 宴会 vi. 参加宴会), to "entertain with good food". 
e.g. If you wine and dine someone, you usually take him out to dinner at a fancy restaurant. 

The company wined and dined us, hoping to convince us we should accept the job.

*** more of a chore than a pleasure
something you do rather unwillingly.
e.g. I think that cooking is more of a chore(n. 讨厌的工作；琐事) than a pleasure.

*** to play with your food
to push food around the plate without eating it

*** dine in
dine at home
e.g. We're dining in tonight.

*** to spoil your appetite
to do something that would hinder(v. 阻碍；打扰) your desire to eat
e.g. Stop talking about the snails, you're spoiling my appetite!

*** to overeat oneself
eat too much, eat immodestly(ad. 不慎地；不客气地).
e.g. If you overeat, you're bound to get fat.

*** to be full-up
to eat to the point that you can't eat anymore.
- Would you like more chips?
- No, thank you, I'm already full-up.

*** home-cooked food
food cooker at home, usually implies that food is healthy.

e.g. Preparing home-cooked food is a good way to make a balanced meal.

*** slap-up meal
large and sumptuous
e.g. I feel like making a slap-up meal tonight.

*** to grab a bite to eat
to eat something quickly
e.g. I won't eat the whole cake, just let me grab a bite to eat.

** Writing Task 1: Vocabulary for Accurate Data
| under 30     | just under 30     | well under 30             |
|--------------+-------------------+---------------------------|
| less than 30 | slightly under 30 | considerably less than 30 |
| below 30     | almost 30         |                           |
|              | nearly 30         |                           |
|              | close to 30       |                           |

| over 20      | just over 20        | well over 20             |
|--------------+---------------------+--------------------------|
| above 20     | slightly over 20    | cosiderably more than 20 |
| more than 20 | marginally above 20 |                          |

We're not sure exactly if it's over or under.

| about 20         |
|------------------|
| approximately 20 |
| around 20        |
| more or less 20  |

** How to Describe a Bar Chart
- Introduction
- Overview
- Body Paragraph A
- Body Paragraph B

1. Introduction (one or two sentences)
The chart illustrates the amount of money spent on 5 consumer goods(cars, computers, books, perfume and cameras) in France and the UK in 2010. Units are measures in pounds sterling(n. 英国货币，英镑).

2. Overview (Highlight key features)
Overall ,the expenaiture of the UK was higher than that of France. Both the French and the British spent the most money on cars while in the UK, the least amount of money was spent on prefume compared to carmeras in France.

3. Body Paragraph
In terms of cars, the UK spent around 450,000 on this as opposed to exactly 400,000 in France. The expenditure on books in the UK was higher than in France(about 400,000 and 300,000 respectively).







 
