* Introduction
  Hello, You'all. This is BoAdBo, looking for more.
** Contest Notification:
   http://www.et-data.com/a-1.html
*** 数据来源

    大赛提供数据为各数据管理机构脱敏后的固定时间段公开数据，包括：

    贵州交通行业数据

    交通运输部出行云平台出行数据

    货车帮的货运数据

    高德地图和路况数据(图盟)

    国家统计局数据

    北京市政务数据

    重庆大数据平台数据

    广东省政府开放数据

    贵州省政府开放数据

    上海市政府开放数据

    广州市政府开放数据

    深圳市政府开放数据

    武汉市政府公开数据

    贵阳市数据开放平台数据

    青岛政务开放数据

    无锡市政府开放数据

    佛山南海区数说南海平台数据

    浙江政务（杭州）开放数据

    多省市历史空气质量数据

    多省市历史天气数据

    中国移动集团贵州分gghk公司脱敏数据

    数据下载地址：

    http://www.et-data.com

    http://www.bdbmc.cn

*** 赛程赛制

    赛程起止时间：2017年5月至9月。

    - （一）报名：

      时间：2017年5月5日至7月17日

      形式：参赛选手在官网报名，并按照要求填写参赛信息、提交项目材料。

    - （二）初赛

      时间：2017年7月18日至7月31日
      
      形式：评委对项目进行线上筛选，评选出60个项目进入复赛，并在官网上公布。

    - （三）复赛

      时间：2017年8月1日至8月27日

      形式：评委对60个进入复赛的项目和10个以内绿色通道项目进行评选，分别在3个重点城市各举行1场现场路演，选拔16-20个项目进入决赛，进入决赛的项目将在官网公布。

    - （四）决赛及颁奖仪式

      时间：2017年8月28日至9月27日

      形式：在贵州省贵阳市举行决赛项目现场路演及答辩，评出奖项并进行颁奖。

*** 本次大赛分两个组别进行比赛，分别为项目赛、算法赛，其中项目赛分开放式和命题两类。

    项目赛（开放式）：涵盖与交通运输行业相关的大数据应用项目或智能硬件项目。

    项目赛（命题式）：A.高速公路绿通车精准画像、B.节假日路网流量预测、C.高速公路异常事件检测、D.城市公交线路优化、E.出行行为分析

    算法赛：根据大赛组委会提供的相关数据资源和方案命题，在规定时间内，提供完整的大数据优化和解决方案。

** Register require project proposal
   
*** TODO Proposal [ ]
    - [ ] Information collecting

    DEADLINE: <2017-07-12 Sun>

* Next step
  1. Need some plan and coffee
  2. Please establish some rules and documentation, looking for more.
  
