* Title

  In many countries, people decide to have children at a later age than in the past? Why? Do advantages of this development outweigh disadvantages?

* Outline
  
** On the big picture, due to over population, people unconsciously decide to delay having kids.

** On the small picture, however, values of people have changed. They no longer consider having kids as a way of improving their life quality, instead, it's considered a heavy weight on both children and parents.

** The benefits of postponing pregnancy can result in considerably fewer population, and more concentrated resources for the children, which in return populate more elites in the society. However, on the down side, we have to deal with the issues with the aging of population.

#+TITLE: Postponing pregnancy, threat or blessness?
#+AUTHOR: king-kong

As many have observed, since the economy boom the world has been dedicated to producing children, and the population grows like snow balls until it suddenly slows down! What happened? It seems like, the rule adopted from biology can still be applied to the human society. An unstoppable growing rate inevitably slows down and finally gets stuck at a finite line.

As the /Solow Growth Model/ would suggest, at first, to accumulate wealth, the society demands more labor, and thus more children are born. With more labor, the society produces more and better goods. It worked until the break of technology. More jobs can be done with fewer man power. As a consequent, the few accumulates more assets, while the majority are suffering from the side effect of over population. Unconsciously, people cease wanting to have kids since having more kids means less room, more effort and less resources for their own, while back in the old days, having more kids means more man power, more labor forces, more wealth in the family. In other words, in a society that is no longer in need of labor but elites, people wouldn't dare to give birth to a child with insufficient resources. 

With the development of the society, many countries have witness the low birth rate, especially in well developed countries. These societies may benefit from less population because of the more elite ratio, since more wealth can be gained with few man. However, on the long term, most of the family in the societies would have to rely on the support of the very few of the young adults. This is called the aging of population. In fact, some of the developed countries are experiencing negative population growth. More and more weight falls to the new generation, less population seems like the perfect way to solve the global warming and other environmental problems, provided that the production capability can meet the needs of people, and more people can benefit from the world economy. Otherwise, it's just poisoning young adults with pressure of supporting their parents and supporting their children.

